export const STAT_COPY = {
  real_traffic: {
    label: "This is your real traffic",
    what: "Verified and likely human sessions in the selected 7, 30, or 90 days. A session is one visit: a run of page views from one visitor.",
    tells: "How many real people came to your site.",
    excludes: "Bots, scanners, and sessions without enough evidence to count as human.",
    empty: "There are no sessions in this window. Traffic in the selected period will fill this number.",
  },
  verified_humans: {
    label: "Verified Humans",
    what: "Sessions where the browser proved itself: the tracker sent screen size, language, page timings, scroll depth, or a click or scroll event.",
    tells: "People we are certain about.",
    excludes: "Log-only visits with no browser signal.",
    empty: "The tracking snippet is not installed or is not reaching Higashi. Install it and send browser signals to fill this number.",
  },
  likely_humans: {
    label: "Likely Humans",
    what: "Sessions without browser proof that arrived from search, social media, or an AI assistant, or read several real pages cleanly without 404s or scanner paths.",
    tells: "People we are fairly sure about; this count is not padded.",
    excludes: "One-page visits with no referrer.",
    empty: "No sessions met these signs in this window. Clean visits from a source or across several pages will fill this number.",
  },
  suspicious_sessions: {
    label: "Suspicious Sessions",
    what: "Sessions with a scanner user agent, a security-probe path such as wp-login, .env, or xmlrpc, a single 404 without a referrer, or only 404s.",
    tells: "Noise that should not be mistaken for visitors.",
    excludes: "Known, named bots; those are counted as bots.",
    empty: "No suspicious sessions were seen in this window. A visit matching a scanner or 404 pattern will fill this number.",
  },
  unknown_sessions: {
    label: "Unknown Sessions",
    what: "Browser-like sessions from server logs with no proof either way.",
    tells: "The part we will not guess about.",
    excludes: "Sessions with enough evidence to classify as human or suspicious.",
    empty: "There are no unresolved browser-like log sessions in this window. A log session without proof either way will appear here.",
  },
  unclassified_sessions: {
    label: "Unclassified Sessions",
    what: "Sessions not yet sorted; this is non-zero for a few minutes after an upgrade while the first pass runs.",
    tells: "The other numbers are still filling in.",
    excludes: "Sessions already sorted into a traffic class.",
    empty: "There are no sessions waiting to be sorted. New unsorted sessions after an upgrade will appear here briefly.",
  },
  ai_crawlers: {
    label: "AI Crawlers",
    what: "Visits by named AI crawlers such as GPTBot, ClaudeBot, Bytespider, PerplexityBot, and ChatGPT-User. For bots, one visit means one request.",
    tells: "How often AI companies fetch your pages.",
    excludes: "Search engine crawlers.",
    empty: "None were seen, or the site is not sending its logs. Named AI crawler requests in the logs will fill this number.",
  },
  known_bots: {
    label: "Known Bots",
    what: "Visits by other named bots, including search engines, SEO tools, and uptime monitors. For bots, one visit means one request.",
    tells: "Non-AI machine traffic, verified where the vendor publishes its ranges.",
    excludes: "AI crawlers, which are counted separately.",
    empty: "No other named bot requests were seen in this window. Their requests in the logs will fill this number.",
  },
  page_views: {
    label: "Page Views",
    what: "Pages served to non-bot sessions, excluding 404s.",
    tells: "Raw volume before the human and bot split.",
    excludes: "Bot requests and 404s.",
    empty: "No eligible page views were recorded in this window. A non-bot visit to a real page will fill this number.",
  },
  errors_404: {
    label: "404 Errors",
    what: "Not-found pages hit by non-bot sessions.",
    tells: "Broken links and probes worth fixing or ignoring.",
    excludes: "Bot 404s.",
    empty: "No non-bot 404s were recorded in this window. A non-bot request for a missing page will fill this number.",
  },
  avg_time_spent: {
    label: "Average Time Spent",
    what: "Average length of a real session.",
    tells: "How long real visitors engage with the site.",
    excludes: "Bots and sessions without a page-leave signal.",
    empty: "This needs the page-leave signal from the tracking snippet. Visits imported from server logs carry no time on page; if most traffic comes from logs, this stays blank until the snippet is on the site.",
  },
  traffic_confidence: {
    label: "Traffic Confidence",
    what: "High means at least one verified human in the window; low means only likely humans; very low means neither; none means no sessions.",
    tells: "How much to trust the real-traffic number.",
    excludes: "It does not add sessions to the count.",
    empty: "There are no sessions in this window. A recorded session will fill this rating.",
  },
  raw_sessions: {
    label: "Raw Sessions",
    what: "Every session in the selected window before any filtering.",
    tells: "The denominator for the traffic split.",
    excludes: "Nothing is filtered out.",
    empty: "There are no sessions in this window. The next recorded session will fill this number.",
  },
  live_now: {
    label: "Live Now",
    what: "Visitors active on the site right now.",
    tells: "Current activity at a glance.",
    excludes: "Earlier visits outside the live period.",
    empty: "The live count has not arrived yet. A successful live update will fill it.",
  },
  traffic_quality: {
    label: "Traffic Quality",
    what: "Log sessions grouped by human proof and noise signals.",
    tells: "How the sessions in this window were classified.",
    excludes: "Named bot requests.",
    empty: "There is no session data in this window. Recorded sessions will fill this breakdown.",
  },
  scanner_noise: {
    label: "Scanner Noise",
    what: "Suspicious sessions grouped by the paths they hit and the reasons they were flagged.",
    tells: "Which scanner patterns account for the noise.",
    excludes: "Known, named bots.",
    empty: "No scanner pattern was detected in this window. A suspicious session will fill this breakdown.",
  },
  scanner_path_hits: {
    label: "Scanner Path Hits",
    what: "Requests to this path from suspicious sessions.",
    tells: "Which paths scanners try most often.",
    excludes: "Requests outside suspicious sessions.",
    empty: "No hits on this path were recorded. A scanner request will fill this count.",
  },
  scanner_reason_sessions: {
    label: "Scanner Reason Sessions",
    what: "Suspicious sessions flagged for this reason.",
    tells: "Which signals identify the scanner noise.",
    excludes: "Sessions without this flag.",
    empty: "No sessions were flagged for this reason. A matching session will fill this count.",
  },
  top_page_views: {
    label: "Page Views",
    what: "Views of this page from real visitors in the selected window.",
    tells: "Which pages real visitors read most.",
    excludes: "Bot requests and 404s.",
    empty: "No real visitor views were recorded for this page. A real visit will fill this count.",
  },
  top_page_time: {
    label: "Page Time",
    what: "Average time real visitors spent on this page.",
    tells: "How long visitors stayed on this page.",
    excludes: "Visits without a page-leave signal.",
    empty: "The tracking snippet has not sent a page-leave signal for this page. That signal will fill this time.",
  },
  top_country_visitors: {
    label: "Country Visitors",
    what: "Real visitors assigned to this country in the selected window.",
    tells: "Where real visitors came from.",
    excludes: "Bots and visitors whose country could not be determined.",
    empty: "No real visitor was assigned to this country. A visit with a known country will fill this count.",
  },
};
